# Generated by Django 5.0.3 on 2024-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company Name')),
                ('price_comfort', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Comfort')),
                ('price_economic', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Economic')),
                ('city_from', models.CharField(max_length=300, verbose_name='From City')),
                ('city_destination', models.CharField(max_length=300, verbose_name='To City')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('comfort_bed_location', models.CharField(max_length=50, verbose_name='Comfort Bed Location')),
                ('economic_seat_location', models.CharField(max_length=50, verbose_name='Economic Seat Location')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
